apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.global.volumes.pgpvc}}
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{.Values.global.volumes.className}}
  volumeMode: {{.Values.global.volumes.mode}}
  selector:
    matchLabels:
      name: {{.Values.global.volumes.pgPvLabel}}
  accessModes:
    - ReadWriteOnce
