
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notejam-front.fullname" . }}
  labels:
    {{- include "notejam-front.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.global.service.serviceport}}
    protocol:  {{.Values.global.service.protocol}}
    targetPort: {{ .Values.global.service.port}}
  - name: https
    port: {{ .Values.global.service.serviceport2}}
    protocol:  {{.Values.global.service.protocol}}
    targetPort: {{ .Values.global.service.port}}
  selector:
    {{- include "notejam-front.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
